document.addEventListener('DOMContentLoaded', () => {
  const translations = {
    ja: {
      title: 'CryptoNavigator | 仮想通貨ポータル',
      badge: 'オールインワン仮想通貨情報ハブ',
      heroDescription:
        '初心者から中級者まで、仮想通貨の学習・比較・最新トレンド追跡をワンストップで提供。取引所・ウォレット・ニュース・AI分析を駆使して、次の一歩をサポートします。',
      heroCTACompare: '取引所を比較',
      heroCTAnewsletter: '最新情報を受け取る',
      heroPanelHeading: '今週の注目トピック',
      heroPanelItem1: 'バイナンスの新規IEO「SolarGrid」参加チャンス',
      heroPanelItem2: 'ETH上海アップグレード後のステーキング動向',
      heroPanelItem3: 'ハードウェアウォレット最新セール情報',
      heroPanelLink: 'インサイダー向け裏技へ →',
      navExchanges: '取引所',
      navCoins: '仮想通貨事典',
      navFresh: '新着',
      navAI: 'AI分析',
      navBlog: 'ブログ',
      navInsider: '裏技',
      languageSelectLabel: '言語を選択',
      languageOptionJA: '日本語',
      languageOptionEN: 'English',
      languageOptionZH: '中文',
      exchangesHeading: '取引所比較ハブ',
      exchangesDescription: '手数料・キャンペーン・特徴から最適な取引所を絞り込みましょう。',
      exchangeFilterLabel: '主な目的で絞り込む:',
      exchangeFilterOptionAll: 'すべて',
      exchangeFilterOptionBeginner: '初心者向け',
      exchangeFilterOptionDefi: 'DeFi対応',
      exchangeFilterOptionNft: 'NFTマーケット',
      exchangeFilterOptionPro: 'ハイレバレッジ',
      exchangeCard1Title: 'コインチェック',
      exchangeCard1Item1: 'スプレッド重視のシンプルUI',
      exchangeCard1Item2: 'キャンペーン: 初回入金で2000円分BTCプレゼント',
      exchangeCard1Item3: '取扱銘柄: BTC/ETH/LSK 他25種',
      exchangeCard1CTA: '口座開設はこちら',
      exchangeCard2Title: 'バイナンス',
      exchangeCard2Item1: '取引手数料0.1%～。BNB保有で割引',
      exchangeCard2Item2: 'キャンペーン: Launchpad「SolarGrid」参加権',
      exchangeCard2Item3: '特徴: DeFi・NFT・先物・レンディングを網羅',
      exchangeCard2CTA: '今すぐ参加',
      exchangeCard3Title: 'Bybit',
      exchangeCard3Item1: '高流動性のデリバティブ取引',
      exchangeCard3Item2: 'キャンペーン: 紹介コードで入金額10%ボーナス',
      exchangeCard3Item3: '特徴: コピー取引・資産運用ツールが充実',
      exchangeCard3CTA: '詳細を見る',
      exchangeCard4Title: 'ビットフライヤー',
      exchangeCard4Item1: '初心者でも安心の国内大手',
      exchangeCard4Item2: 'キャンペーン: 友達紹介でBTC5000円分',
      exchangeCard4Item3: '特徴: 独自NFTマーケットプレイス「bafy」',
      exchangeCard4CTA: '今すぐ登録',
      coinsHeading: 'ジャンル別仮想通貨事典',
      coinsDescription: 'ミーム・アルト・ステーブルなどカテゴリごとに整理。検索で目的のコインを探せます。',
      coinSearchPlaceholder: 'コイン名やカテゴリで検索',
      coin1Title: 'Dogecoin (DOGE)',
      coin1Description: 'ミームコインの代表格。コミュニティドリブンで、決済導入が徐々に進行。',
      coin1Tag: '#ミーム',
      coin2Title: 'Solana (SOL)',
      coin2Description: '高速・低コストのL1。DeFiやNFTエコシステムが拡大中。',
      coin2Tag: '#アルト',
      coin3Title: 'Arbitrum (ARB)',
      coin3Description: 'EthereumのLayer2。手数料削減と高速化でDeFiの人気が上昇。',
      coin3Tag: '#Layer2',
      coin4Title: 'USD Coin (USDC)',
      coin4Description: '米ドル連動型ステーブルコイン。透明性とコンプライアンスに注力。',
      coin4Tag: '#ステーブル',
      coin5Title: 'Pepe (PEPE)',
      coin5Description: 'ミームコミュニティ発のトークン。SNSでのバズを活かした拡散が武器。',
      coin5Tag: '#ミーム',
      coin6Title: 'Chainlink (LINK)',
      coin6Description: '分散型オラクルネットワーク。スマートコントラクトに外部データを提供。',
      coin6Tag: '#インフラ',
      freshHeading: '新上場＆注目プロジェクト速報',
      freshDescription: '話題のIEO/IDOや急上昇トークンの注目ポイントをいち早くキャッチ。',
      freshTimeline1Title: 'SolarGrid (SLR)',
      freshTimeline1Description: '再生可能エネルギー発電量をトークナイズ。Binance Launchpadでトークン販売開始。',
      freshTimeline1Link: '詳細と参加方法',
      freshTimeline2Title: 'NeoDex (NDEX)',
      freshTimeline2Description: 'AI自動化を備えたDEX。上場直後からTVL 5000万ドル突破。',
      freshTimeline2Link: '注目ポイントを見る',
      freshTimeline3Title: 'MetaVerseX (MVX)',
      freshTimeline3Description: 'メタバース向けのインタラクティブNFTマーケット。Epic Gamesと提携発表。',
      freshTimeline3Link: 'IEOスケジュール',
      aiHeading: 'AIによるBTC動向シナリオ',
      aiDescription: '価格データ・オンチェーン指標・マクロ情報を学習した独自モデルがシナリオを提示。',
      aiScenarioBull: '強気シナリオ（45%）',
      aiScenarioBullText: 'ETF資金流入とハッシュレート上昇が継続。来月の目標価格は <strong>￥9,800,000</strong>。',
      aiScenarioNeutral: '中立シナリオ（35%）',
      aiScenarioNeutralText: 'マクロイベント待ちのレンジ推移。サポート帯は <strong>￥8,400,000</strong>。',
      aiScenarioBear: '弱気シナリオ（20%）',
      aiScenarioBearText: '金利上昇がリスク資産を圧迫。主要サポート割れで <strong>￥7,500,000</strong> まで調整。',
      aiButton: '週次レポートを購読',
      aiChartHeading: '今週のテクニカル指標',
      aiChartItem1: '200日移動平均: 価格が6%上回る',
      aiChartItem2: 'RSI: 58（中立〜強気）',
      aiChartItem3: 'ネットポジション変化: クジラの保有量 +2.4%',
      aiChartItem4: '為替相関: DXYとの相関 -0.32',
      aiChartNote: '※AIモデルは4時間ごとに更新。登録ユーザーは詳細レポートにアクセス可能。',
      blogHeading: '最新記事＆ハウツー',
      blogDescription: '仮想通貨の基礎から税金対策、ステーキング戦略まで幅広く解説。',
      blogArticle1Title: '【保存版】初めてのビットコイン購入ガイド',
      blogArticle1Description: 'ウォレット準備から取引所登録、初回取引のポイントを初心者向けに丁寧に解説。',
      blogArticle2Title: 'アルトコイン投資で押さえるべき5つの指標',
      blogArticle2Description: '時価総額、FDV、ロックアップ率、開発アクティビティ、コミュニティ熱量を分析。',
      blogArticle3Title: 'DeFiで利回りを最大化する裏技ポートフォリオ',
      blogArticle3Description: 'レンディング、ステーキング、リキッドステーキングの組み合わせ戦略を公開。',
      blogArticleLink: '読む →',
      insiderHeading: 'インサイダー向け裏技＆ツール',
      insiderDescription: 'アフィリエイト収益とユーザー満足度を高める秘策をまとめました。',
      insiderTile1Title: 'エアドロップカレンダー',
      insiderTile1Description: '条件・締切・必要タスクをリスト化。メールリマインド機能で参加率アップ。',
      insiderTile1Link: 'テンプレートをダウンロード',
      insiderTile2Title: '税金対策ツール',
      insiderTile2Description: '損益通算シートと確定申告チェックリストで税務の不安を解消。',
      insiderTile2Link: '税理士を紹介',
      insiderTile3Title: 'ゲーミフィケーション企画',
      insiderTile3Description: 'ユーザー投票で注目アルトを決定。参加者には限定NFTやポイントを付与。',
      insiderTile3Link: '企画の成功事例',
      insiderTile4Title: 'API連携ダッシュボード',
      insiderTile4Description: 'DeFi利回りとレンディング金利を自動更新。スポンサー枠で広告枠を創出。',
      insiderTile4Link: 'プロトタイプを見る',
      newsletterHeading: '週次ニュースレターを購読',
      newsletterDescription: '最新ニュース、AIシナリオ、限定キャンペーン情報をメールでお届け。',
      newsletterPlaceholder: 'メールアドレス',
      newsletterButton: '登録する',
      footerDescription: '仮想通貨の学習から投資判断まで、信頼できる情報でサポートします。',
      footerLink1: '運営会社',
      footerLink2: '広告掲載',
      footerLink3: 'プライバシーポリシー',
      footerCopy: '© 2024 CryptoNavigator. All rights reserved.'
    },
    en: {
      title: 'CryptoNavigator | Crypto Portal',
      badge: 'All-in-one crypto intelligence hub',
      heroDescription:
        'From beginners to intermediate investors, access learning resources, comparisons, and trend tracking in one place. Exchanges, wallets, news, and AI analysis guide your next move.',
      heroCTACompare: 'Compare exchanges',
      heroCTAnewsletter: 'Get the latest updates',
      heroPanelHeading: 'This week’s highlights',
      heroPanelItem1: 'Binance Launchpad IEO “SolarGrid” now open',
      heroPanelItem2: 'Staking landscape after the Ethereum Shanghai upgrade',
      heroPanelItem3: 'Fresh hardware wallet discount campaigns',
      heroPanelLink: 'Explore insider tips →',
      navExchanges: 'Exchanges',
      navCoins: 'Coin encyclopedia',
      navFresh: 'New listings',
      navAI: 'AI outlook',
      navBlog: 'Blog',
      navInsider: 'Pro tools',
      languageSelectLabel: 'Choose language',
      languageOptionJA: '日本語',
      languageOptionEN: 'English',
      languageOptionZH: '中文',
      exchangesHeading: 'Exchange comparison hub',
      exchangesDescription: 'Filter top exchanges by fees, promotions, and key strengths.',
      exchangeFilterLabel: 'Filter by primary goal:',
      exchangeFilterOptionAll: 'All',
      exchangeFilterOptionBeginner: 'Beginner friendly',
      exchangeFilterOptionDefi: 'DeFi ready',
      exchangeFilterOptionNft: 'NFT marketplace',
      exchangeFilterOptionPro: 'High leverage',
      exchangeCard1Title: 'Coincheck',
      exchangeCard1Item1: 'Simple UI with tight spreads',
      exchangeCard1Item2: 'Promo: Earn ¥2,000 in BTC with first deposit',
      exchangeCard1Item3: 'Listed coins: BTC/ETH/LSK +25 more',
      exchangeCard1CTA: 'Open an account',
      exchangeCard2Title: 'Binance',
      exchangeCard2Item1: 'Trading fees from 0.1%; hold BNB for discounts',
      exchangeCard2Item2: 'Promo: Launchpad access to “SolarGrid”',
      exchangeCard2Item3: 'Features: DeFi, NFT, futures, and lending suite',
      exchangeCard2CTA: 'Join now',
      exchangeCard3Title: 'Bybit',
      exchangeCard3Item1: 'Deep liquidity for derivatives',
      exchangeCard3Item2: 'Promo: 10% deposit bonus via referral code',
      exchangeCard3Item3: 'Highlights: Copy trading and wealth tools',
      exchangeCard3CTA: 'View details',
      exchangeCard4Title: 'bitFlyer',
      exchangeCard4Item1: 'Trusted domestic leader for new investors',
      exchangeCard4Item2: 'Promo: Refer friends, earn ¥5,000 in BTC',
      exchangeCard4Item3: 'Feature: Exclusive “bafy” NFT marketplace',
      exchangeCard4CTA: 'Register today',
      coinsHeading: 'Coin encyclopedia by theme',
      coinsDescription: 'Browse meme, alt, stable, and more categories to find the project you need.',
      coinSearchPlaceholder: 'Search coins or categories',
      coin1Title: 'Dogecoin (DOGE)',
      coin1Description: 'The archetypal meme coin backed by its community; payments adoption keeps growing.',
      coin1Tag: '#Meme',
      coin2Title: 'Solana (SOL)',
      coin2Description: 'High-speed, low-cost L1 powering a booming DeFi and NFT ecosystem.',
      coin2Tag: '#Alt',
      coin3Title: 'Arbitrum (ARB)',
      coin3Description: 'Ethereum Layer 2 scaling network driving down fees and boosting DeFi usage.',
      coin3Tag: '#Layer2',
      coin4Title: 'USD Coin (USDC)',
      coin4Description: 'USD-pegged stablecoin focused on transparency and compliance.',
      coin4Tag: '#Stable',
      coin5Title: 'Pepe (PEPE)',
      coin5Description: 'Viral meme token leveraging social buzz for exponential reach.',
      coin5Tag: '#Meme',
      coin6Title: 'Chainlink (LINK)',
      coin6Description: 'Decentralized oracle network feeding smart contracts with external data.',
      coin6Tag: '#Infrastructure',
      freshHeading: 'Fresh listings & spotlight projects',
      freshDescription: 'Catch IEO/IDO launches and fast-rising tokens before everyone else.',
      freshTimeline1Title: 'SolarGrid (SLR)',
      freshTimeline1Description: 'Tokenizing renewable energy output; public sale live on Binance Launchpad.',
      freshTimeline1Link: 'Details & how to join',
      freshTimeline2Title: 'NeoDex (NDEX)',
      freshTimeline2Description: 'AI-driven DEX automation hits $50M TVL right after listing.',
      freshTimeline2Link: 'See why it matters',
      freshTimeline3Title: 'MetaVerseX (MVX)',
      freshTimeline3Description: 'Interactive NFT marketplace for the metaverse backed by Epic Games.',
      freshTimeline3Link: 'IEO timeline',
      aiHeading: 'AI-powered BTC outlook scenarios',
      aiDescription: 'Our proprietary model blends price, on-chain, and macro signals to project scenarios.',
      aiScenarioBull: 'Bullish scenario (45%)',
      aiScenarioBullText: 'ETF inflows and rising hash rate persist. Next month’s target: <strong>¥9,800,000</strong>.',
      aiScenarioNeutral: 'Neutral scenario (35%)',
      aiScenarioNeutralText: 'Range-bound while awaiting macro catalysts. Support zone near <strong>¥8,400,000</strong>.',
      aiScenarioBear: 'Bearish scenario (20%)',
      aiScenarioBearText: 'Higher rates pressure risk assets. Breakdown could revisit <strong>¥7,500,000</strong>.',
      aiButton: 'Subscribe to weekly report',
      aiChartHeading: 'Technical dashboard of the week',
      aiChartItem1: '200-day MA: price trading 6% above',
      aiChartItem2: 'RSI: 58 (neutral to bullish)',
      aiChartItem3: 'Net positions: whale holdings up 2.4%',
      aiChartItem4: 'FX correlation: DXY correlation at -0.32',
      aiChartNote: 'AI model refreshes every 4 hours. Members access deeper breakdowns.',
      blogHeading: 'Latest articles & how-tos',
      blogDescription: 'Wide coverage from crypto basics to tax hacks and staking strategies.',
      blogArticle1Title: 'Essential guide: buying bitcoin for the first time',
      blogArticle1Description: 'Step-by-step walkthrough from wallet prep to first trade tips for beginners.',
      blogArticle2Title: '5 metrics every altcoin investor should track',
      blogArticle2Description: 'Market cap, FDV, vesting, dev activity, and community momentum explained.',
      blogArticle3Title: 'DeFi yield-maximizing playbook of pro tactics',
      blogArticle3Description: 'Combine lending, staking, and liquid staking for optimal returns.',
      blogArticleLink: 'Read →',
      insiderHeading: 'Insider growth hacks & tools',
      insiderDescription: 'Strategies to boost affiliate revenue while delighting your audience.',
      insiderTile1Title: 'Airdrop calendar',
      insiderTile1Description: 'Track requirements, deadlines, and tasks. Email reminders raise participation.',
      insiderTile1Link: 'Download template',
      insiderTile2Title: 'Tax optimization toolkit',
      insiderTile2Description: 'PnL worksheet and filing checklist that calm crypto tax worries.',
      insiderTile2Link: 'Meet trusted tax pros',
      insiderTile3Title: 'Gamified rankings',
      insiderTile3Description: 'Let voters crown top altcoins. Reward them with exclusive NFTs or points.',
      insiderTile3Link: 'Success stories',
      insiderTile4Title: 'API-powered dashboard',
      insiderTile4Description: 'Auto-refresh DeFi yields and lending rates with sponsor-ready slots.',
      insiderTile4Link: 'View prototype',
      newsletterHeading: 'Subscribe to the weekly newsletter',
      newsletterDescription: 'Get breaking news, AI scenarios, and exclusive promos straight to your inbox.',
      newsletterPlaceholder: 'Email address',
      newsletterButton: 'Sign up',
      footerDescription: 'Trusted insights guiding your journey from learning to investing.',
      footerLink1: 'About us',
      footerLink2: 'Advertise',
      footerLink3: 'Privacy policy',
      footerCopy: '© 2024 CryptoNavigator. All rights reserved.'
    },
    zh: {
      title: 'CryptoNavigator | 加密貨幣資訊入口',
      badge: '一站式加密資訊樞紐',
      heroDescription:
        '從新手到進階投資者，一站掌握學習資源、比較工具與最新趨勢。結合交易所、錢包、新聞與AI分析，幫助你做出下一步決策。',
      heroCTACompare: '比較交易所',
      heroCTAnewsletter: '訂閱最新情報',
      heroPanelHeading: '本週焦點',
      heroPanelItem1: '幣安 Launchpad 新IEO「SolarGrid」開放參與',
      heroPanelItem2: '以太坊上海升級後的質押趨勢',
      heroPanelItem3: '硬體錢包最新優惠整理',
      heroPanelLink: '查看進階秘訣 →',
      navExchanges: '交易所',
      navCoins: '加密百科',
      navFresh: '新上架',
      navAI: 'AI 解析',
      navBlog: '部落格',
      navInsider: '高手工具',
      languageSelectLabel: '選擇語言',
      languageOptionJA: '日本語',
      languageOptionEN: 'English',
      languageOptionZH: '中文',
      exchangesHeading: '交易所比較中心',
      exchangesDescription: '依照手續費、活動與特色快速鎖定最適合的交易所。',
      exchangeFilterLabel: '依主要目的篩選：',
      exchangeFilterOptionAll: '全部',
      exchangeFilterOptionBeginner: '新手友善',
      exchangeFilterOptionDefi: '支援 DeFi',
      exchangeFilterOptionNft: 'NFT 市場',
      exchangeFilterOptionPro: '高槓桿',
      exchangeCard1Title: 'Coincheck',
      exchangeCard1Item1: '重視點差的簡潔介面',
      exchangeCard1Item2: '活動：首次入金送 2,000 日圓等值 BTC',
      exchangeCard1Item3: '支援幣種：BTC/ETH/LSK 等 25 種',
      exchangeCard1CTA: '立即開戶',
      exchangeCard2Title: 'Binance',
      exchangeCard2Item1: '手續費最低 0.1%，持有 BNB 再享折扣',
      exchangeCard2Item2: '活動：Launchpad「SolarGrid」參與權',
      exchangeCard2Item3: '特色：涵蓋 DeFi、NFT、合約與理財',
      exchangeCard2CTA: '立刻加入',
      exchangeCard3Title: 'Bybit',
      exchangeCard3Item1: '高流動性的衍生品交易',
      exchangeCard3Item2: '活動：推薦碼入金享 10% 獎勵',
      exchangeCard3Item3: '特色：複製交易與資產管理工具齊全',
      exchangeCard3CTA: '查看詳情',
      exchangeCard4Title: 'bitFlyer',
      exchangeCard4Item1: '日本主流平台，新手也安心',
      exchangeCard4Item2: '活動：好友推薦獲得 5,000 日圓 BTC',
      exchangeCard4Item3: '特色：自家「bafy」NFT 市場',
      exchangeCard4CTA: '立即註冊',
      coinsHeading: '主題式加密貨幣百科',
      coinsDescription: '依照迷因、山寨、穩定幣等類別整理，快速搜尋想了解的項目。',
      coinSearchPlaceholder: '搜尋幣種或分類',
      coin1Title: 'Dogecoin (DOGE)',
      coin1Description: '迷因幣代表作，由社群推動，支付應用持續擴張。',
      coin1Tag: '#迷因',
      coin2Title: 'Solana (SOL)',
      coin2Description: '高速低成本的一層公鏈，DeFi 與 NFT 生態蓬勃發展。',
      coin2Tag: '#山寨',
      coin3Title: 'Arbitrum (ARB)',
      coin3Description: '以太坊 Layer2 擴容方案，降低手續費並提升 DeFi 熱度。',
      coin3Tag: '#Layer2',
      coin4Title: 'USD Coin (USDC)',
      coin4Description: '與美元掛鉤的穩定幣，重視透明度與合規。',
      coin4Tag: '#穩定幣',
      coin5Title: 'Pepe (PEPE)',
      coin5Description: '迷因社群發起的代幣，透過社群聲量迅速傳播。',
      coin5Tag: '#迷因',
      coin6Title: 'Chainlink (LINK)',
      coin6Description: '去中心化預言機網路，為智慧合約提供外部資料。',
      coin6Tag: '#基礎設施',
      freshHeading: '新幣上市與焦點項目速報',
      freshDescription: '第一時間掌握熱門 IEO/IDO 與快速上漲的代幣亮點。',
      freshTimeline1Title: 'SolarGrid (SLR)',
      freshTimeline1Description: '再生能源發電量代幣化，Binance Launchpad 正式開賣。',
      freshTimeline1Link: '參與教學',
      freshTimeline2Title: 'NeoDex (NDEX)',
      freshTimeline2Description: '內建 AI 自動化的 DEX，上線即突破 5,000 萬美元 TVL。',
      freshTimeline2Link: '了解亮點',
      freshTimeline3Title: 'MetaVerseX (MVX)',
      freshTimeline3Description: '面向元宇宙的互動式 NFT 市場，宣布與 Epic Games 合作。',
      freshTimeline3Link: 'IEO 行程',
      aiHeading: 'AI 推演 BTC 走勢情境',
      aiDescription: '專屬模型結合價格、鏈上與宏觀數據，提供多種走勢推估。',
      aiScenarioBull: '多頭情境（45%）',
      aiScenarioBullText: 'ETF 資金持續流入、算力上升。下月目標價 <strong>¥9,800,000</strong>。',
      aiScenarioNeutral: '中性情境（35%）',
      aiScenarioNeutralText: '等待宏觀事件，區間震盪。支撐落在 <strong>¥8,400,000</strong>。',
      aiScenarioBear: '空頭情境（20%）',
      aiScenarioBearText: '利率走高壓抑風險資產，跌破關鍵支撐恐回測 <strong>¥7,500,000</strong>。',
      aiButton: '訂閱週報',
      aiChartHeading: '本週技術指標',
      aiChartItem1: '200 日均線：價格高出 6%',
      aiChartItem2: 'RSI：58（中性偏多）',
      aiChartItem3: '籌碼變化：巨鯨持倉增加 2.4%',
      aiChartItem4: '匯率相關性：與 DXY 的相關係數 -0.32',
      aiChartNote: 'AI 模型每 4 小時更新一次，會員可查看完整報告。',
      blogHeading: '最新文章與操作指南',
      blogDescription: '從加密入門、節稅技巧到質押策略，全面掌握。',
      blogArticle1Title: '新手必讀：第一次購入比特幣全攻略',
      blogArticle1Description: '從錢包準備、交易所註冊到首筆交易重點，逐步教學。',
      blogArticle2Title: '投資山寨幣必看的五大指標',
      blogArticle2Description: '解析市值、完全稀釋估值、解鎖節奏、開發活躍度與社群熱度。',
      blogArticle3Title: 'DeFi 高收益布局的進階技巧',
      blogArticle3Description: '結合借貸、質押與流動性代幣，打造最佳化報酬。',
      blogArticleLink: '閱讀更多 →',
      insiderHeading: '進階變現秘技與工具',
      insiderDescription: '提升聯盟收益並強化使用者體驗的實用策略。',
      insiderTile1Title: '空投行事曆',
      insiderTile1Description: '整理參與條件、截止日與任務，郵件提醒提高完成率。',
      insiderTile1Link: '下載範本',
      insiderTile2Title: '稅務優化工具包',
      insiderTile2Description: '損益試算表與報稅清單，減少加密稅務焦慮。',
      insiderTile2Link: '聯繫專業稅務師',
      insiderTile3Title: '遊戲化排名活動',
      insiderTile3Description: '用戶票選熱門山寨幣，參與者可獲限定 NFT 或積分。',
      insiderTile3Link: '成功案例',
      insiderTile4Title: 'API 整合儀表板',
      insiderTile4Description: '自動更新 DeFi 收益與借貸利率，並預留贊助曝光位。',
      insiderTile4Link: '查看原型',
      newsletterHeading: '訂閱每週電子報',
      newsletterDescription: '掌握最新新聞、AI 情境與專屬活動，一封信全收。',
      newsletterPlaceholder: '電子郵件',
      newsletterButton: '立即訂閱',
      footerDescription: '從學習到投資決策，我們以可信資訊陪你前進。',
      footerLink1: '關於我們',
      footerLink2: '廣告合作',
      footerLink3: '隱私權政策',
      footerCopy: '© 2024 CryptoNavigator. All rights reserved.'
    }
  };

  const languageSelect = document.getElementById('language-select');

  const applyLanguage = (lang) => {
    const dictionary = translations[lang] ?? translations.ja;
    document.documentElement.lang = lang;
    document.title = dictionary.title;

    document.querySelectorAll('[data-i18n]').forEach((el) => {
      const key = el.dataset.i18n;
      const translation = dictionary[key];
      if (translation) {
        el.innerHTML = translation;
      }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
      const key = el.dataset.i18nPlaceholder;
      const translation = dictionary[key];
      if (translation) {
        el.setAttribute('placeholder', translation);
      }
    });

    document.querySelectorAll('[data-i18n-aria-label]').forEach((el) => {
      const key = el.dataset.i18nAriaLabel;
      const translation = dictionary[key];
      if (translation) {
        el.setAttribute('aria-label', translation);
      }
    });
  };

  const savedLanguage = localStorage.getItem('preferredLanguage');
  const initialLanguage = savedLanguage && translations[savedLanguage] ? savedLanguage : 'ja';
  applyLanguage(initialLanguage);

  if (languageSelect) {
    languageSelect.value = initialLanguage;
    languageSelect.addEventListener('change', () => {
      const selected = languageSelect.value;
      applyLanguage(selected);
      localStorage.setItem('preferredLanguage', selected);
    });
  }

  const exchangeFilter = document.getElementById('exchange-filter');
  const exchangeCards = document.querySelectorAll('#exchange-cards .card');
  const coinSearch = document.getElementById('coin-search');
  const coinTiles = document.querySelectorAll('#coin-grid .tile');

  if (exchangeFilter) {
    exchangeFilter.addEventListener('change', () => {
      const value = exchangeFilter.value;
      exchangeCards.forEach((card) => {
        if (value === 'all') {
          card.classList.remove('is-hidden');
          return;
        }
        const tags = card.dataset.tags?.split(' ') ?? [];
        card.classList.toggle('is-hidden', !tags.includes(value));
      });
    });
  }

  if (coinSearch) {
    coinSearch.addEventListener('input', () => {
      const keyword = coinSearch.value.trim().toLowerCase();
      coinTiles.forEach((tile) => {
        const name = tile.dataset.name ?? '';
        const tags = tile.dataset.tags ?? '';
        const text = `${name} ${tags}`.toLowerCase();
        tile.classList.toggle('is-hidden', keyword && !text.includes(keyword));
      });
    });
  }
});
